### ISSUE TITLE
Operands could not be broadcast together with shapes (13, 128, 13) (13, 128, 128)

### ISSUE THREAD

**Issue by CatalinVulcan** [ameraner/dsen2-cr#10]
I'm trying to use the pre-trained model for prediction using the following command:

`python dsen2cr_main.py --predict model_SARcarl.hdf5`

But I'm getting the following error. Do you have any idea why this is?

> Traceback (most recent call last):
>   File "dsen2cr_main.py", line 198, in <module>
>     run_dsen2cr(args.predict_file, args.resume_file)
>   File "dsen2cr_main.py", line 145, in run_dsen2cr
>     include_sar_input=include_sar_input)
>   File "C:\Users\Catalin\Desktop\cloud removal\dsen2cr_network.py", line 52, in DSen2CR_model
>     x = Add()([x, input_opt])
>   File "C:\Users\Catalin\Soft\anaconda3\dsen2cr_env\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 824, in __call__
>     self._maybe_build(inputs)
>   File "C:\Users\Catalin\Soft\anaconda3\dsen2cr_env\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2146, in _maybe_build
>     self.build(input_shapes)
>   File "C:\Users\Catalin\Soft\anaconda3\dsen2cr_env\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py", line 306, in wrapper
>     output_shape = fn(instance, input_shape)
>   File "C:\Users\Catalin\Soft\anaconda3\dsen2cr_env\lib\site-packages\tensorflow_core\python\keras\layers\merge.py", line 111, in build
>     output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
>   File "C:\Users\Catalin\Soft\anaconda3\dsen2cr_env\lib\site-packages\tensorflow_core\python\keras\layers\merge.py", line 82, in _compute_elemwise_op_output_shape
>     'together with shapes ' + str(shape1) + ' ' + str(shape2))
> ValueError: Operands could not be broadcast together with shapes (13, 128, 13) (13, 128, 128)

**Comment by CatalinVulcan** [comment]
Thank you for your reply. It had to do with the version of Numpy. But in the end, I couldn't make it work due to library versioning and compatibility.

Using 

`conda install -c conda-forge python=3.7 tensorflow-gpu=1.15.0 keras=2.2.4 numpy scipy rasterio pydot graphviz h5py`,

resulted in installing some package versions that gave errors when running the code. I tried changing the versions, but every time I changed one, other errors and incompatibilities appeared until I reached a point I simply couldn't solve.

For input, I used images from the dataset mentioned in the README. It might help to include 3 images in the repository as well, along with the appropriate `datasetfilelist.csv`. This might make things simpler.

**Comment by ameraner** [comment]
Ah, yeah. Unfortunately I have no means atm to try to update the code for newer package versions. If you ever get it running, feel free to open a PR or propose changes! Also, good point about the images..

**Comment by ameraner** [comment]
@animecomico has reported in https://github.com/ameraner/dsen2-cr/issues/6#issuecomment-1229429215 that this works: 
```
conda create -y -n dsen2_cr_v1 python=3.7.0
conda activate dsen2_cr_v1
conda install numpy=1.17.5
pip install tensorflow==1.13.2
pip install keras==2.2.4
pip install matplotlib==2.1.1
pip install rasterio
pip install pydot
pip install h5py
pip install graphviz
pip install scipy
pip install protobuf==3.6.1
```

**Comment by zhaojun-110** [comment]
Thanks for you perfect job and code.
I am use tensorflow_gpu=1.13, Keras_gpu=2.2.4:
Traceback (most recent call last):
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_main.py", line 182, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_main.py", line 171, in run_dsen2cr
    input_shape, max_queue_size, use_multi_processing, workers)
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_tools.py", line 130, in train_dsen2cr
    workers=workers)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

Then, i changed the model.fit_generation(verbose=0):
Traceback (most recent call last):
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_main.py", line 182, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_main.py", line 171, in run_dsen2cr
    input_shape, max_queue_size, use_multi_processing, workers)
  File "/home/chang/Code/image fusion/dsen2-cr/Code/dsen2cr_tools.py", line 130, in train_dsen2cr
    workers=workers)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/chang/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 429, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'

I want to know what should i do then?
Looking forward your reply
