### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by s86707** [ameraner/dsen2-cr#11]
Hi,  I'm using my own Input-Data and I'm becoming the: Index Error: list out of range. 

Here is the full issue:

Traceback (most recent call last):
  File "dsen2cr_main.py", line 179, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 160, in run_dsen2cr
    max_val_sar, scale)
  File "C:\Users\maria\Documents\GitHub\dsen2-cr\Code\dsen2cr_tools.py", line 169, in predict_dsen2cr
    for i, (data, y) in enumerate(predict_generator):
  File "C:\Users\maria\anaconda3\envs\dsen2cr\lib\site-packages\keras\utils\data_utils.py", line 372, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "C:\Users\maria\anaconda3\envs\dsen2cr\lib\site-packages\keras\utils\data_utils.py", line 372, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "C:\Users\maria\Documents\GitHub\dsen2-cr\Code\tools\dataIO.py", line 280, in __getitem__
    self.random_crop_paramy[indexes])
  File "C:\Users\maria\Documents\GitHub\dsen2-cr\Code\tools\dataIO.py", line 308, in __data_generation
    random_crop_paramy_temp, data_type=3)
  File "C:\Users\maria\Documents\GitHub\dsen2-cr\Code\tools\dataIO.py", line 407, in get_batch
    data_image = self.get_data_image(ID, data_type, random_crop_paramx_temp[i], random_crop_paramy_temp[i])
  File "C:\Users\maria\Documents\GitHub\dsen2-cr\Code\tools\dataIO.py", line 354, in get_data_image
    data_path = os.path.join(self.input_data_folder, ID[data_type], ID[4]).lstrip()
IndexError: list index out of range

The output folder is also created but don't get any output images. 
It wolud be very nice if someone could give me an advice for this error.

**Comment by ameraner** [comment]
Hi @s86707 , thank you for your issue. The error message points to an issue in your data .csv file (I assume that the list out-of-range error comes from the `ID` indexing). Are you sure that your csv file has the correct number of columns, as here https://github.com/ameraner/dsen2-cr/blob/main/Data/datasetfilelist.csv? You could also check that it is being read correctly by checking the outputs of this function: https://github.com/ameraner/dsen2-cr/blob/59e81ae0d013bcae992d078e92a1175cc4cbf257/Code/tools/dataIO.py#L40

**Comment by ameraner** [comment]
Hi @s86707 , it's a different error, but it sounds similar to what has been reported here by @CatalinVulcan https://github.com/ameraner/dsen2-cr/issues/10#issuecomment-1649595207 - maybe also for you it's a numpy version issue?

**Comment by zhaotianle123** [comment]
I had the same problem as you, can I ask how you solved it in the end?

**Comment by ameraner** [comment]
@CatalinVulcan reported that by downgrading numpy he got a bit farther, but then had other incompatibility issues. If you ever get it running, feel free to open a PR or propose changes.

**Comment by ameraner** [comment]
I'm closing this issue since the original issue is solved, and the second issue is reported in https://github.com/ameraner/dsen2-cr/issues/10
