### ISSUE TITLE
I have tested the model model_SARcarl.hdf5

### ISSUE THREAD

**Issue by devbangi** [ameraner/dsen2-cr#23]
I have tested the model model_SARcarl.hdf5 with this .csv:
![image](https://github.com/ameraner/dsen2-cr/assets/96576249/789dec40-87e5-4d76-bf9f-390026b34ce4)

having previously made the changes: 
![image](https://github.com/ameraner/dsen2-cr/assets/96576249/93dc240d-b462-47c8-920d-4953d04750df)
and 
![image](https://github.com/ameraner/dsen2-cr/assets/96576249/ecadc91a-b84a-4bb5-a9bf-1f739fb23e6c)

but I got the following result, which doesn't seem good to me... am I wrong?
![image](https://github.com/ameraner/dsen2-cr/assets/96576249/470fae35-9e7e-4285-a4b5-b6a430bf758a)

**Comment by 123eye** [comment]
你好 我想请问一下为什么我运行的时候报Traceback (most recent call last):
  File "dsen2cr_main.py", line 180, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 161, in run_dsen2cr
    max_val_sar, scale)
  File "/root/autodl-tmp/dsen2-cr/Code/dsen2cr_tools.py", line 172, in predict_dsen2cr
    eval_results = model.test_on_batch(data, y)
  File "/root/miniconda3/envs/dd/lib/python3.7/site-packages/keras/engine/training.py", line 1256, in test_on_batch
    outputs = self.test_function(ins)
  File "/root/miniconda3/envs/dd/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/root/miniconda3/envs/dd/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/root/miniconda3/envs/dd/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,13,128,128] vs. shape[2] = [16,1,128,128]
         [[{{node lambda_17/concat}}]]这个错误，你是怎么解决的

**Comment by ameraner** [comment]
Hi, I'm sorry, from this I have no way to understand what is going sideways...

**Comment by Dhruv-Sanghavi** [comment]
hey, @ameraner can you please share your output image. I am also facing same issue.

**Comment by YashNathani45** [comment]
> hey, [@ameraner](https://github.com/ameraner) can you please share your output image. I am also facing same issue.

Yes, predicted image is not good. @ameraner would love if you could help us with this :)

**Comment by Dargon2023** [comment]
> I have tested the model model_SARcarl.hdf5 with this .csv: ![image](https://github.com/ameraner/dsen2-cr/assets/96576249/789dec40-87e5-4d76-bf9f-390026b34ce4)
> 
> having previously made the changes: ![image](https://github.com/ameraner/dsen2-cr/assets/96576249/93dc240d-b462-47c8-920d-4953d04750df) and ![image](https://github.com/ameraner/dsen2-cr/assets/96576249/ecadc91a-b84a-4bb5-a9bf-1f739fb23e6c)
> 
> but I got the following result, which doesn't seem good to me... am I wrong? ![image](https://github.com/ameraner/dsen2-cr/assets/96576249/470fae35-9e7e-4285-a4b5-b6a430bf758a)
I have also encountered this problem at present. Have you finally solved it?
