### ISSUE TITLE
Cannot run main code (Permission Error)

### ISSUE THREAD

**Issue by duyhoangatk** [ameraner/dsen2-cr#26]
Hi ameraner,
I'm new to Ubuntu LST and also cloud removal. I have tried to run the main code but I have encountered this problem:

Model compiled successfully!
Getting file lists
Number of train files found:  3
Number of validation files found:  3
Number of test files found:  3
Training model name: DSen2-CR_001
Traceback (most recent call last):
  File "dsen2cr_main.py", line 179, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 168, in run_dsen2cr
    input_shape, max_queue_size, use_multi_processing, workers)
  File "/home/atk/dsen2-cr/Code/dsen2cr_tools.py", line 19, in train_dsen2cr
    out_path_train = make_dir(os.path.join(base_out_path, model_name))
  File "/home/atk/dsen2-cr/Code/tools/dataIO.py", line 18, in make_dir
    os.makedirs(dir_path)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/path'

How can I fix this ?
Waiting for your reply. Thank you very much.

**Comment by ameraner** [comment]
Hi @duyhoangatk , I believe you still need to modify the paths here, from the default placeholder path to something specific to your machine: https://github.com/ameraner/dsen2-cr/blob/fa996d747671b1ae7bfdb7f8e9c3d88345e4fdb7/Code/dsen2cr_main.py#L58

I'll close the issue, but feel free to reopen/comment if needed! 
Cheers,
Andrea

**Comment by duyhoangatk** [comment]
Hi ameraner,
Thank you for your reply. I realized two lines of base_out_path and input_data_folder in dsen2cr.main.py
But I'm completely new to this one (also Ubuntu LST), so I'm still resreaching and studying the code.
I have few following questions:
1. If I want to get input data and export base output data from a specific place (ex: input: C/input  ; output: C/output), are these following codes correct ? (sorry if my question is sound silly)
 base_out_path = '/mnt/c/input'
 input_data_folder = '/mnt/c/output'
2. For the input data, what is the type of data (GeoTIFF or JPG or something ?). And if GeoTIFF file can be used as input data, can I use the GeoTIFF file from Copernicus Dataspace Browser ? (link: https://browser.dataspace.copernicus.eu/)

Waiting for your reply. Thank you very much

**Comment by ameraner** [comment]
Hi, 
the paths seem sensible, as long as you can access it from where the code is being run.
The code expects GeoTiff (see https://github.com/ameraner/dsen2-cr/blob/fa996d747671b1ae7bfdb7f8e9c3d88345e4fdb7/Code/tools/dataIO.py#L329). I did not try to use the Copernicus Dataspace data directly, I don't know how it is stored there, if the range is the same etc.... but you can try and see!

**Comment by duyhoangatk** [comment]
Hi ameraner,
I have changed the path and the code seems working, but then I encoutered this problem:

(dsen2cr_env) atk@atkttwc0725:~/dsen2-cr/Code$ python dsen2cr_main.py
Using TensorFlow backend.
WARNING:tensorflow:From dsen2cr_main.py:101: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From dsen2cr_main.py:109: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2024-07-02 09:48:48.908067: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2024-07-02 09:48:48.936132: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2024-07-02 09:48:48.939889: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fffc016e750 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-07-02 09:48:48.940803: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-07-02 09:48:48.947947: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-07-02 09:48:48.948967: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2024-07-02 09:48:48.950286: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (atkttwc0725): /proc/driver/nvidia/version does not exist
WARNING:tensorflow:From dsen2cr_main.py:115: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:199: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:206: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /home/atk/dsen2-cr/Code/tools/image_metrics.py:45: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1521: The name tf.log is deprecated. Please use tf.math.log instead.

Model compiled successfully!
Getting file lists
Number of train files found:  3
Number of validation files found:  3
Number of test files found:  3
Training model name: DSen2-CR_001
Model information files created at  /mnt/c/dsen2cr/output/DSen2-CR_001
Generator initialized
Generator initialized
Generator initialized
Training starts...
WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py:848: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py:850: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From /home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py:856: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Epoch 1/8
Traceback (most recent call last):
  File "dsen2cr_main.py", line 179, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 168, in run_dsen2cr
    input_shape, max_queue_size, use_multi_processing, workers)
  File "/home/atk/dsen2-cr/Code/dsen2cr_tools.py", line 130, in train_dsen2cr
    workers=workers)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/atk/miniconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

How can I fix this ?
Sorry if I will ask many others questions in the future but I'm using this for my current work.
Waiting for your reply. Thank you very much.

**Comment by ameraner** [comment]
Could you check the answers here? https://stackoverflow.com/questions/57857683/attributeerror-progbarlogger-object-has-no-attribute-log-values/59337511
