### ISSUE TITLE
Run the pretrained model

### ISSUE THREAD

**Issue by fekenzofugi** [ameraner/dsen2-cr#29]
I would like to know how I can run the pretrained model available in this repository. Could you provide detailed instructions on how to set up and run the model?

Thank you in advance for your help!

**Comment by ameraner** [comment]
Hi, have you read and tried the commands here? https://github.com/ameraner/dsen2-cr?tab=readme-ov-file#basic-commands The Readme is currently the only documentation I can provide. I'll close the issue, please open a new specific issue if you have futher issues when running the code.

**Comment by fekenzofugi** [comment]
![image](https://github.com/user-attachments/assets/99f483af-0bfe-486e-a93d-11a77b3b5832)

**Comment by fekenzofugi** [comment]
![image](https://github.com/user-attachments/assets/2ec8994f-e8db-4e99-ace1-ee572f67a77e)

This is the error that i'm facing.

**Comment by fekenzofugi** [comment]
![image](https://github.com/user-attachments/assets/64888b10-48ac-4760-b46d-24c95c41526a)

**Comment by ameraner** [comment]
Could you try to change the code here https://github.com/ameraner/dsen2-cr/blob/main/Code/tools/dataIO.py#L23 to 
```python 
def get_train_val_test_filelists(listpath): 
    with open(listpath) as f: 
        reader = csv.reader(f, delimiter='\t') 
        filelist = list(reader) 
  
        train_filelist = [] 
        val_filelist = [] 
        test_filelist = [] 
        for  f in filelist: 
            line_entries = f[0].split(sep=", ") 
            if line_entries[0] == '1': 
                train_filelist.append(f) 
            if line_entries[0] == '2': 
                val_filelist.append(f) 
            if line_entries[0] == '3': 
                test_filelist.append(f) 
    return  train_filelist, val_filelist, test_filelist 

```
and see if it helps?

**Comment by fekenzofugi** [comment]
Thank you very much!
It worked. But i've got a different error:
```
Traceback (most recent call last):
  File "dsen2cr_main.py", line 177, in <module>
    run_dsen2cr(args.predict_file, args.resume_file)
  File "dsen2cr_main.py", line 158, in run_dsen2cr
    max_val_sar, scale)
  File "/home/nipe/dsen2-cr/Code/dsen2cr_tools.py", line 172, in predict_dsen2cr
    eval_results = model.test_on_batch(data, y)
  File "/home/nipe/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/engine/training.py", line 1256, in test_on_batch
    outputs = self.test_function(ins)
  File "/home/nipe/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/nipe/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/nipe/anaconda3/envs/dsen2cr_env/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,13,128,128] vs. shape[2] = [16,1,128,128]
         [[{{node lambda_17/concat}}]]
```

**Comment by ameraner** [comment]
great :) feel free to open a Pull Request with the change if you have the chance.

**Comment by ameraner** [comment]
@fekenzofugi if you got the model to run (also going past the other issues), I'd love to get a PR :)

**Comment by fekenzofugi** [comment]
I'll create the PR right away.
